experiment:
  name: default_experiment
  seed: 42
  output_dir: results/

mode: train

data:
  root_dir: ./datasets
  version: dataset_20221008
  num_classes: 29
  split: test
  use_rgb_masks: false
  color_map_csv: ListOfClassesAndColorCodes.csv
  img_size: 512
  batch_size: 4
  workers: 4

model:
  name: deeplabv3plus
  backbone: resnet50
  pretrained: true

train:
  epochs: 15
  lr: 1e-4
  optimizer: adam
  scheduler: step
  step_size: 5
  gamma: 1

loss:
  type: dice_ce   # options: ce, dice, dice_ce, weighted_ce
  alpha: 0.7
  class_weights:

    bckgnd: 0.05
    padding: 0.05
    ribbons: 1.0
    gridline: 1.0
    inactive: 2.0
    crack: 3.0
    other: 0.8

logging:
  use_wandb: false
  print_freq: 1
  save_best_only: true

device: cuda
